trigger: none
pr: none

parameters:  
  - name: environment
    displayName: Environment
    type: string
    default: 'pre'
  - name: workers
    displayName: Number of Workers
    type: string
    default: '1'
  - name: seleniumGrid
    displayName: Selenium Grid URL
    type: string
    default: 'http://localhost:4444'
  - name: deviceName
    displayName: Device Name
    type: string
    default: 'Windows'
  - name: bsOSVersion
    displayName: BrowserStack OS Version
    type: string
    default: '11'
  - name: bsBrowserVersion
    displayName: BrowserStack Browser Version
    type: string
    default: 'latest'
  - name: target
    displayName: Target Browser
    type: string
    default: 'Chrome'
  - name: isEmulationEnabled
    displayName: Enable Emulation
    type: string
    default: 'false'
  - name: emulateDeviceInfo
    displayName: Emulated Device Info
    type: string
    default: 'iPhone 12 Pro'
  - name: isAccessibilityEnabled
    displayName: Is Accessibility Run Enabled
    type: boolean
    default: false
  - name: enableRetry
    displayName: Enable Failed Test Retry
    type: boolean
    default: false

stages:

  - stage: IPAFF_OPS_CHEDA
    displayName: IPAFF OPS - CHEDA
    variables:
      - template: 'variables/IPAFF/${{parameters.environment}}.yml'
    jobs:
      - template: run-test-template.yml
        parameters:
          jobName: IPAFF_OPS_CHEDA
          environment: ${{ parameters.environment }}
          branchName: $(Build.SourceBranch)
          seleniumGrid: ${{ parameters.seleniumGrid }}
          deviceName: ${{ parameters.deviceName }}
          bsOSVersion: ${{ parameters.bsOSVersion }}
          workers: ${{ parameters.workers }}
          bsBrowserVersion: 'latest'
          target: ${{ parameters.target }}
          isEmulationEnabled: ${{ parameters.isEmulationEnabled }}
          emulateDeviceInfo: ${{ parameters.emulateDeviceInfo }}
          isAccessibilityEnabled: ${{ parameters.isAccessibilityEnabled }}
          enableRetry: ${{ parameters.enableRetry }}
          application: 'IPAFF'
          dependsOn: ''
          filterTestCases: 'TestCategory=CHEDA'

  - stage: IPAFF_OPS_CHEDD
    displayName: IPAFF OPS - CHEDD
    dependsOn: IPAFF_OPS_CHEDA
    condition: always()
    variables:
      - template: 'variables/IPAFF/${{parameters.environment}}.yml'
    jobs:
      - template: run-test-template.yml
        parameters:
          jobName: IPAFF_OPS_CHEDD
          environment: ${{ parameters.environment }}
          branchName: $(Build.SourceBranch)
          seleniumGrid: ${{ parameters.seleniumGrid }}
          deviceName: ${{ parameters.deviceName }}
          bsOSVersion: ${{ parameters.bsOSVersion }}
          workers: ${{ parameters.workers }}
          bsBrowserVersion: 'latest'
          target: ${{ parameters.target }}
          isEmulationEnabled: ${{ parameters.isEmulationEnabled }}
          emulateDeviceInfo: ${{ parameters.emulateDeviceInfo }}
          isAccessibilityEnabled: ${{ parameters.isAccessibilityEnabled }}
          enableRetry: ${{ parameters.enableRetry }}
          application: 'IPAFF'
          dependsOn: ''
          filterTestCases: 'TestCategory=CHEDD'

  - stage: IPAFF_OPS_CHEDP
    displayName: IPAFF OPS - CHEDP
    dependsOn: IPAFF_OPS_CHEDD
    condition: always()
    variables:
      - template: 'variables/IPAFF/${{parameters.environment}}.yml'
    jobs:
      - template: run-test-template.yml
        parameters:
          jobName: IPAFF_OPS_CHEDP
          environment: ${{ parameters.environment }}
          branchName: $(Build.SourceBranch)
          seleniumGrid: ${{ parameters.seleniumGrid }}
          deviceName: ${{ parameters.deviceName }}
          bsOSVersion: ${{ parameters.bsOSVersion }}
          workers: ${{ parameters.workers }}
          bsBrowserVersion: 'latest'
          target: ${{ parameters.target }}
          isEmulationEnabled: ${{ parameters.isEmulationEnabled }}
          emulateDeviceInfo: ${{ parameters.emulateDeviceInfo }}
          isAccessibilityEnabled: ${{ parameters.isAccessibilityEnabled }}
          enableRetry: ${{ parameters.enableRetry }}
          application: 'IPAFF'
          dependsOn: ''
          filterTestCases: 'TestCategory=CHEDP'

  - stage: IPAFF_OPS_CHEDPP
    displayName: IPAFF OPS - CHEDPP
    dependsOn: IPAFF_OPS_CHEDP
    condition: always()
    variables:
      - template: 'variables/IPAFF/${{parameters.environment}}.yml'
    jobs:
      - template: run-test-template.yml
        parameters:
          jobName: IPAFF_OPS_CHEDPP
          environment: ${{ parameters.environment }}
          branchName: $(Build.SourceBranch)
          seleniumGrid: ${{ parameters.seleniumGrid }}
          deviceName: ${{ parameters.deviceName }}
          bsOSVersion: ${{ parameters.bsOSVersion }}
          workers: ${{ parameters.workers }}
          bsBrowserVersion: 'latest'
          target: ${{ parameters.target }}
          isEmulationEnabled: ${{ parameters.isEmulationEnabled }}
          emulateDeviceInfo: ${{ parameters.emulateDeviceInfo }}
          isAccessibilityEnabled: ${{ parameters.isAccessibilityEnabled }}
          enableRetry: ${{ parameters.enableRetry }}
          application: 'IPAFF'
          dependsOn: ''
          filterTestCases: 'TestCategory=CHEDPP'