trigger: none
pr: none

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: 'pre'
  - name: workers
    displayName: Number of Workers
    type: string
    default: '4'
  - name: seleniumGrid
    displayName: Selenium Grid URL
    type: string
    default: 'http://localhost:4444'
  - name: deviceName
    displayName: Device Name
    type: string
    default: 'Windows'
  - name: bsOSVersion
    displayName: BrowserStack OS Version
    type: string
    default: '11'
  - name: bsBrowserVersion
    displayName: BrowserStack Browser Version
    type: string
    default: 'latest'
  - name: target
    displayName: Target Browser
    type: string
    default: 'Chrome'
  - name: isEmulationEnabled
    displayName: Enable Emulation
    type: string
    default: 'false'
  - name: emulateDeviceInfo
    displayName: Emulated Device Info
    type: string
    default: 'iPhone 12 Pro'
  - name: isAccessibilityEnabled
    displayName: Is Accessibility Run Enabled
    type: boolean
    default: false
  - name: enableRetry
    displayName: Enable Failed Test Retry
    type: boolean
    default: false
  - name: featureFilter
    displayName: 'Run specific scenario(s) by tag (e.g. SPS-9414 or SPS-9414,SPS-9419 or RiskEngine-CHEDPP). Leave as "all" to run all Risk Engine tests.'
    type: string
    default: 'all'

stages:

  - ${{ if eq(parameters.featureFilter, 'all') }}:
    - stage: IPAFF_OPS_RISK_ENGINE_BULK_UPLOAD
      displayName: IPAFF OPS - Risk Engine - Bulk Uploads
      variables:
        - template: 'variables/IPAFF/${{ parameters.environment }}.yml'
      jobs:
        - template: run-test-template.yml
          parameters:
            jobName: IPAFF_OPS_RISK_ENGINE_BULK_UPLOAD
            environment: ${{ parameters.environment }}
            branchName: $(Build.SourceBranch)
            seleniumGrid: ${{ parameters.seleniumGrid }}
            deviceName: ${{ parameters.deviceName }}
            bsOSVersion: ${{ parameters.bsOSVersion }}
            workers: ${{ parameters.workers }}
            bsBrowserVersion: 'latest'
            target: ${{ parameters.target }}
            isEmulationEnabled: ${{ parameters.isEmulationEnabled }}
            emulateDeviceInfo: ${{ parameters.emulateDeviceInfo }}
            isAccessibilityEnabled: ${{ parameters.isAccessibilityEnabled }}
            enableRetry: ${{ parameters.enableRetry }}
            application: 'IPAFF'
            dependsOn: ''
            filterTestCases: ''
            featureFilter: 'BulkUpload'

    - stage: IPAFF_OPS_RISK_ENGINE_CHEDA
      displayName: IPAFF OPS - Risk Engine - CHEDA
      dependsOn: IPAFF_OPS_RISK_ENGINE_BULK_UPLOAD
      condition: always()
      variables:
        - template: 'variables/IPAFF/${{ parameters.environment }}.yml'
      jobs:
        - template: run-test-template.yml
          parameters:
            jobName: IPAFF_OPS_RISK_ENGINE_CHEDA
            environment: ${{ parameters.environment }}
            branchName: $(Build.SourceBranch)
            seleniumGrid: ${{ parameters.seleniumGrid }}
            deviceName: ${{ parameters.deviceName }}
            bsOSVersion: ${{ parameters.bsOSVersion }}
            workers: '1'
            bsBrowserVersion: 'latest'
            target: ${{ parameters.target }}
            isEmulationEnabled: ${{ parameters.isEmulationEnabled }}
            emulateDeviceInfo: ${{ parameters.emulateDeviceInfo }}
            isAccessibilityEnabled: ${{ parameters.isAccessibilityEnabled }}
            enableRetry: ${{ parameters.enableRetry }}
            application: 'IPAFF'
            dependsOn: ''
            filterTestCases: ''
            featureFilter: 'SPS-9523,SPS-9524'

    - stage: IPAFF_OPS_RISK_ENGINE_CHEDD
      displayName: IPAFF OPS - Risk Engine - CHEDD
      dependsOn: IPAFF_OPS_RISK_ENGINE_CHEDA
      condition: always()
      variables:
        - template: 'variables/IPAFF/${{ parameters.environment }}.yml'
      jobs:
        - template: run-test-template.yml
          parameters:
            jobName: IPAFF_OPS_RISK_ENGINE_CHEDD
            environment: ${{ parameters.environment }}
            branchName: $(Build.SourceBranch)
            seleniumGrid: ${{ parameters.seleniumGrid }}
            deviceName: ${{ parameters.deviceName }}
            bsOSVersion: ${{ parameters.bsOSVersion }}
            workers: '1'
            bsBrowserVersion: 'latest'
            target: ${{ parameters.target }}
            isEmulationEnabled: ${{ parameters.isEmulationEnabled }}
            emulateDeviceInfo: ${{ parameters.emulateDeviceInfo }}
            isAccessibilityEnabled: ${{ parameters.isAccessibilityEnabled }}
            enableRetry: ${{ parameters.enableRetry }}
            application: 'IPAFF'
            dependsOn: ''
            filterTestCases: ''
            featureFilter: 'SPS-9521,SPS-9522'

    - stage: IPAFF_OPS_RISK_ENGINE_CHEDP
      displayName: IPAFF OPS - Risk Engine - CHEDP
      dependsOn: IPAFF_OPS_RISK_ENGINE_CHEDD
      condition: always()
      variables:
        - template: 'variables/IPAFF/${{ parameters.environment }}.yml'
      jobs:
        - template: run-test-template.yml
          parameters:
            jobName: IPAFF_OPS_RISK_ENGINE_CHEDP
            environment: ${{ parameters.environment }}
            branchName: $(Build.SourceBranch)
            seleniumGrid: ${{ parameters.seleniumGrid }}
            deviceName: ${{ parameters.deviceName }}
            bsOSVersion: ${{ parameters.bsOSVersion }}
            workers: '1'
            bsBrowserVersion: 'latest'
            target: ${{ parameters.target }}
            isEmulationEnabled: ${{ parameters.isEmulationEnabled }}
            emulateDeviceInfo: ${{ parameters.emulateDeviceInfo }}
            isAccessibilityEnabled: ${{ parameters.isAccessibilityEnabled }}
            enableRetry: ${{ parameters.enableRetry }}
            application: 'IPAFF'
            dependsOn: ''
            filterTestCases: ''
            featureFilter: 'SPS-9519,SPS-9520'

    - stage: IPAFF_OPS_RISK_ENGINE_CHEDPP
      displayName: IPAFF OPS - Risk Engine - CHEDPP
      dependsOn: IPAFF_OPS_RISK_ENGINE_CHEDP
      condition: always()
      variables:
        - template: 'variables/IPAFF/${{ parameters.environment }}.yml'
      jobs:
        - template: run-test-template.yml
          parameters:
            jobName: IPAFF_OPS_RISK_ENGINE_CHEDPP
            environment: ${{ parameters.environment }}
            branchName: $(Build.SourceBranch)
            seleniumGrid: ${{ parameters.seleniumGrid }}
            deviceName: ${{ parameters.deviceName }}
            bsOSVersion: ${{ parameters.bsOSVersion }}
            workers: '1'
            bsBrowserVersion: 'latest'
            target: ${{ parameters.target }}
            isEmulationEnabled: ${{ parameters.isEmulationEnabled }}
            emulateDeviceInfo: ${{ parameters.emulateDeviceInfo }}
            isAccessibilityEnabled: ${{ parameters.isAccessibilityEnabled }}
            enableRetry: ${{ parameters.enableRetry }}
            application: 'IPAFF'
            dependsOn: ''
            filterTestCases: ''
            featureFilter: 'SPS-9449,SPS-9450,SPS-9507,SPS-9508,SPS-9509,SPS-9510,SPS-9512,SPS-9513,SPS-9514'

  - ${{ if ne(parameters.featureFilter, 'all') }}:
    - stage: IPAFF_OPS_RISK_ENGINE_CUSTOM
      displayName: 'IPAFF OPS - Risk Engine - ${{ parameters.featureFilter }}'
      variables:
        - template: 'variables/IPAFF/${{ parameters.environment }}.yml'
      jobs:
        - template: run-test-template.yml
          parameters:
            jobName: IPAFF_OPS_RISK_ENGINE_CUSTOM
            environment: ${{ parameters.environment }}
            branchName: $(Build.SourceBranch)
            seleniumGrid: ${{ parameters.seleniumGrid }}
            deviceName: ${{ parameters.deviceName }}
            bsOSVersion: ${{ parameters.bsOSVersion }}
            workers: ${{ parameters.workers }}
            bsBrowserVersion: 'latest'
            target: ${{ parameters.target }}
            isEmulationEnabled: ${{ parameters.isEmulationEnabled }}
            emulateDeviceInfo: ${{ parameters.emulateDeviceInfo }}
            isAccessibilityEnabled: ${{ parameters.isAccessibilityEnabled }}
            enableRetry: ${{ parameters.enableRetry }}
            application: 'IPAFF'
            dependsOn: ''
            filterTestCases: 'TestCategory=RiskEngine'
            featureFilter: ${{ parameters.featureFilter }}